name: deepdream
channels:
  - pytorch
dependencies:
  - python=3.8
  - pip
  - tqdm=4.65
  - matplotlib=3.1
  - pytorch=1.5
  - torchvision=0.6
  - pip:
      - numpy==1.18.4
      - scipy==1.5.1
      - opencv-python==4.2.0.32
      - imageio==2.9.0